### PR TITLE
Allow effect plugins, update to Python 3, fix windows

### PR DESCRIPTION
**Pull request by shenberg**
A bunch of changes:

1. Added a function to accept input audio and feed it into the VST plugin
2. Updated to use Python 3 instead of 2
3. Contributed by Lior Hakim: Build instructions for Windows

### CODE REVIEW

**Comment by shenberg** [comment]
Added another important piece of functionality: support for shell plugins. The code always created the first available plugin contained in the loaded module, however for example Waves Audio plugins are all wrapped by a single VST plugin called Waveshell, and you need to choose the actual plugin you wish to use. I added a Python API to get a {Plugin Name : Plugin Index} dictionary, and an additional parameter to load_plugin. The jupyter notebook "Use NS1 example.ipynb" shows how to use this to run NS1 Mono through Waveshell.

**Comment by turian** [comment]
I would also love Python 3 builds for Linux, if you could share them. I would gladly add it to my repo: https://github.com/turian/renderman-dexed-linux

**Comment by fedden** [comment]
Please excuse my inactivity on this - it's been a weird year - @shenberg this looks awesome. I've sent you an invite to be a collaborator. Thank you for your contributions

**Comment by turian** [comment]
@fedden thank you for your amazing work on this project, it is amazing and makes many people happy. Don't worry, it's been a weird year for everyone :)

**Comment by max-prtsr** [comment]
@turian merge maybe then? :)

**Comment by turian** [comment]
@max-prtsr I am not the owner of this repo and I do not have collaborator privileges

**Comment by max-prtsr** [comment]
@fedden could you please give collaborator priveleges to @shenberg 

@turian sorry, wrong call :)

**Comment by fedden** [comment]
I have - the offer has been pending for some time! There should be an email deep in @shenberg's inbox... I'll merge for now and if anyone else needs collaborator access for future PRs feel welcome to request it. Cheers 👍

**Comment by shenberg** [comment]
Spotify created a library for this exact use-case called pedalboard, it's a big project: https://github.com/spotify/pedalboard

**Pull request merged**
